timerecording:
  messaging:
    brokers: sulky-01.srvs.cloudkafka.com:9094,sulky-03.srvs.cloudkafka.com:9094,sulky-02.srvs.cloudkafka.com:9094
    groupId: vgns6bra-consumer
    topic: vgns6bra-add-and-book-businessday
    consumer-enabled: true
  auth:
    username: username
    password: pw
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:file:./data/application;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always